#!/bin/bash
#scrapy crawl login -o live.json -t json
#scrapy crawl conversation -o conversations.json -t json
#scrapy crawl message -o messages.json -t json

scrapy crawl pokemon -o pokemon.json -t json
